---
include:
  - project: ruvu/environment
    file: ROS.gitlab-ci.yml

variables:
  BUILD_TOOL: colcon
  PACKAGES: >
    packman_hardware

foxy-build-on-schedule:
  extends: .build-on-schedule
  variables:
    ROS_DISTRO: foxy
foxy-build:
  extends: .build
  variables:
    ROS_DISTRO: foxy
foxy-test:
  extends: .test
  variables:
    ROS_DISTRO: foxy
foxy-release:
  extends: .release
  variables:
    ROS_DISTRO: foxy
