min_particles: 500
max_particles: 1000

kld_err: 0.01
kld_z: 0.99

odom_model_type: diff-corrected
odom_alpha1: 0.1 # Specifies the expected noise in odometry's rotation estimate from the rotational component of the robot's motion.
odom_alpha2: 0.1 # Specifies the expected noise in odometry's rotation estimate from translational component of the robot's motion.
odom_alpha3: 0.1 # Specifies the expected noise in odometry's translation estimate from the translational component of the robot's motion.
odom_alpha4: 0.1 # Specifies the expected noise in odometry's translation estimate from the rotational component of the robot's motion.

laser_model_type: likelihood_field
laser_z_hit: 0.5
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_likelihood_max_dist: 10.0

update_min_d: 0.025
update_min_a: 0.025

resample_interval: 1
transform_tolerance: 0.1
recovery_alpha_slow: 0.2
recovery_alpha_fast: 0.2

initial_cov_xx: 0.001
initial_cov_yy: 0.001
initial_cov_aa: 0.001

tf_broadcast: true

use_map_topic: true
first_map_only: false
