joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'left_wheel'
  right_wheel: 'right_wheel'
  publish_rate: 50.0               # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 1.0, 1.0, 1.0, 0.001]
  twist_covariance_diagonal: [0.001, 0.001, 1.0, 1.0, 1.0, 0.001]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  # wheel_separation: 0.56
  # wheel_radius: 0.125

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0  # default: 1.0
  wheel_radius_multiplier    : 7  # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.1

  # Base frame_id
  base_frame_id: base_link

  linear:
    x:
      has_velocity_limits    : true
      min_velocity           : -2 # m/s
      max_velocity           : 2  # m/s
      has_acceleration_limits: false
      has_jerk_limits        : false
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1  # rad/s
      has_acceleration_limits: false
      has_jerk_limits        : false
  
  publish_cmd: true
  allow_multiple_cmd_vel_publishers: false

packman_hardware:
  can_device: can0
  loop_hz: 50
  cycle_time_error_threshold: 0.01
