joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'left_wheel'
  right_wheel: 'right_wheel'
  publish_rate: 50.0               # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 1.0, 1.0, 1.0, 0.001]
  twist_covariance_diagonal: [0.001, 0.001, 1.0, 1.0, 1.0, 0.001]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation: 0.56
  wheel_radius: 0.125

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0  # default: 1.0
  wheel_radius_multiplier    : 1.0  # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.1

  # Base frame_id
  base_frame_id: base_link

  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.75  # m/s
      min_velocity           : -0.75 # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.8  # m/s^2
      min_acceleration       : -0.8 # m/s^2
      has_jerk_limits        : true
      max_jerk               : 7.7  # m/s^3
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 0.8  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 0.85  # rad/s^2
      has_jerk_limits        : true
      max_jerk               : 8.0  # rad/s^3

exr1:
  can_device: can0
  frequency: 100
