#!/usr/bin/env bash

# Copyright 2020 RUVU Robotics B.V.

set -e


if [ "$#" -ne 1 ]; then
    echo "usage: $0 [mapname]"
    exit 1
fi

MAP_DIR=${ROS_HOME-~/.ros}/maps

# Create the directory is it does not exists yet
mkdir -p $MAP_DIR

echo "Let's copy the map data"
install "$(ros2 pkg prefix packman_intelligence_bringup --share)/maps/$1.pgm" "$MAP_DIR/map.pgm"
install "$(ros2 pkg prefix packman_intelligence_bringup --share)/maps/$1.yaml" "$MAP_DIR/map.yaml"
echo "Done!"
