footprint:
  - [0.4, 0.3]
  - [0.4, -0.3]
  - [-0.4, -0.3]
  - [-0.4, 0.3]
footprint_padding: 0.0

obstacles_layer:
  observation_sources: scan
  scan:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    min_obstacle_height: -2.0
    max_obstacle_height: 2.0
    obstacle_range: 5.0
    raytrace_range: 6.0

inflater_layer:
  inflation_radius: 1.1
  cost_scaling_factor: 1
