global_frame: map
rolling_window: false

update_frequency: 5.0
publish_frequency: 5.0

width: 100
origin_x: -50
height: 100
origin_y: -50
resolution: 0.025

plugins:
  - {name: static_map, type: "costmap_2d::StaticLayer"}
  - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}
