controller_manager:
  ros__parameters:
    update_rate: 2  # Hz

    forward_command_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_controller:
      type: joint_state_controller/JointStateController

forward_command_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: velocity
