controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_controller:
      type: joint_state_controller/JointStateController

# forward_command_controller:
#   ros__parameters:
#     joints:
#       - joint1
#       - joint2
#     interface_name: velocity

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel"]
    right_wheel_names: ["right_wheel"]
    write_op_modes: ["motor_controller"]

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation: 0.56
    wheel_radius: 0.125

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0  # theoretically 1
    left_wheel_radius_multiplier: 7.3  # theoretically 7
    right_wheel_radius_multiplier: 7.3  # theoretically 7

    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 1.0, 1.0, 1.0, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 1.0, 1.0, 1.0, 0.001]

    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.1
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    linear:
      x:
        has_velocity_limits    : true
        min_velocity           : -2.0 # m/s
        max_velocity           : 2.0  # m/s
        has_acceleration_limits: false
        has_jerk_limits        : false
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.0  # rad/s
        has_acceleration_limits: false
        has_jerk_limits        : false
